#!/bin/bash
#

clear

echo "======================================================="
echo "======== Setting up Raspberry Pi WiFi hotspot ========="
echo "======================================================="

echo "Installing dependencies"

sudo apt-get -y -qq install hostapd udhcpd

cd ./config-files

####################################################################
#	check for and back up existing config files
#################################################################### 

echo "Backing up existing config files"

if [ -f /etc/udhcpd.conf ]
then
    cp /etc/udhcpd.conf /etc/udhcpd.conf.old 
fi

if [ -f /etc/default/udhcpd ]
then
    cp /etc/default/udhcpd /etc/default/udhcpd.old
fi

if [ -f /etc/network/interfaces ]
then
    cp /etc/network/interfaces /etc/network/interfaces.old
fi

if [ -f /etc/hostapd/hostapd.conf ]
then
    cp /etc/hostapd/hostapd.conf /etc/hostapd/hostapd.conf.old
fi

if [ -f /etc/default/hostapd ]
then
    cp /etc/default/hostapd /etc/default/hostapd.old
fi

if [ -f /etc/sysctl.conf ]
then
    cp /etc/sysctl.conf /etc/sysctl.conf.old
fi


if [ -f /etc/iptables.ipv4.nat ]
then
    cp /etc/iptables.ipv4.nat /etc/iptables.ipv4.nat.old
fi


echo "Config Files backed up"

####################################################################
#	copy configs to relevant directories
####################################################################

echo "Configuring DHCP"
sudo cp ./udhcpd.conf /etc
sudo cp ./udhcpd /etc/default

echo "Configuring interfaces"
sudo cp ./interfaces /etc/network

echo "Configuring hostapd"
sudo cp ./hostapd.conf /etc/hostapd
sudo cp ./hostapd /etc/default

echo "Configuring NAT"
sudo cp ./sysctl.conf /etc

echo "Configuring iptables"
sudo cp ./iptables.ipv4.nat /etc

sudo touch /var/lib/misc/udhcpd.leases

echo "Initialising access point"
sudo service hostapd start
sudo update-rc.d hostapd enable

echo "Initialising DHCP server"
sudo service udhcpd start
sudo update-rc.d udhcpd enable

clear 

echo "================================================================"
echo "=================== Configuration complete! ===================="
echo "================================================================"

echo "+++++++++++++++++  REBOOTING in 10 SECONDS  ++++++++++++++++++++"
echo "++++++++++++++++++++++ CTL-C to cancel ++++++++++++++++++++++++"
sleep 10
sudo reboot





